version: '2.1'
services:
  pgdb:
    image: postgres:9.6-alpine
    volumes:
      - pgdb_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis:3.2-alpine
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
  app:
    image: demo-docker:master
    ports:
      - 3000:3000
    depends_on:
      - pgdb
      - redis
volumes:
  pgdb_data:
    driver: local
  redis_data:
    driver: local
